print("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"[::-1])
print(' ')
print("The quick brown fox jumps over the lazy dog several times in a row just to see if the dog could catch up"[::-1])
print(' ')
print("Count Dracula is the title character of Bram Stoker's 1897 gothic horror novel Dracula. He is considered the prototypical and archetypal vampire in subsequent works of fiction. Aspects of the character are believed by some to have been inspired by the 15th-century Wallachian prince Vlad the Impaler, who was also known as Vlad Dracula, and by Sir Henry Irving and Jacques Damala, actors with aristocratic backgrounds that Stoker had met during his life."[::-1])