def solve(s, a):
    result = 0
    max_score = len(s) * 5

    for i in range(len(s)):
        if s[i] == a[i]:
            result += 5
        else:
            result -= 1

    return int(result / max_score * 100)


print(solve("ABCABCABCABCABCABC", "BBACBAAACBBCABCABB"))
print(solve("CAADACDBDCCCABBBBAACCDDCCCDBACDBCBBDABBBDAABADDBBC", "DCDCCADCBBDCBCACBAACABDCADCBABCBBDDCACDDABAABAACCA"))
print(solve("EDBEEABADABBCBEAECAABCEDABCAEACEBAEEECCEACEDAEDEAEEBCDEAEDEEEECCBBBAECBDDEAADAABCCBBCCECDDCEBECBBCBDBCBEDDBDAE", "EDBAEABACABBDBEAECAABCEDABCAEBCCBAEACCCEACEDAEDEAEDBEDEAEDEECECCBBBEECBCDAAADAEAECEDCCECDDCEDACBCCBDBCCEDBBEAD"))
